import Intro from "@/app/components/Intro/Intro";
import { render, screen } from "@testing-library/react";

describe("Intro", () => {
    it("should render the intro header", () => {
        render(<Intro />);
        const header = screen.getByText("How It Works");
        expect(header).toBeInTheDocument();
    });

    it("should render the intro description", () => {
        render(<Intro />);
        const description = screen.getByText("The answers generated by this chatbot are supported by a vast and growing knowledgebase of cyber security information.");
        expect(description).toBeInTheDocument();
    });

    it("should render the use cases section", () => {
        render(<Intro />);
        const useCases = screen.getByText("Examples of use cases for the chatbot are outlined below:");
        expect(useCases).toBeInTheDocument();
    });

    it("should render the sources and links section", () => {
        render(<Intro />);
        const sources = screen.getByText("Cyber Security Information Sources");
        expect(sources).toBeInTheDocument();
    });

    it("should render the sources and links description", () => {
        render(<Intro />);
        const sourcesDescription = screen.getByText("The chatbot uses a variety of sources to generate its responses, including:");
        expect(sourcesDescription).toBeInTheDocument();
    });

    it("should render a link to the CVE website", () => {
        render(<Intro />);
        const cveLink = screen.getByText("Common Vulnerabilities and Exposures (CVE) database");
        expect(cveLink).toBeInTheDocument();
    });

    it("should render a link to CyBOK PDFs", () => {
        render(<Intro />);
        const cybokLink = screen.getByText("Cyber Security Body of Knowledge (CyBOK) PDFs");
        expect(cybokLink).toBeInTheDocument();
    });

    it("should render a link to the CISA website", () => {
        render(<Intro />);
        const cisaLink = screen.getByText("Cyber Security Alerts & Advisories");
        expect(cisaLink).toBeInTheDocument();
    });

    // Potentially more for the internal sources used

    it("should render a link to the NCSC website", () => {
        render(<Intro />);
        const ncscLink = screen.getByText("NCSC Cyber Security Guidance");
        expect(ncscLink).toBeInTheDocument();
    });

    it("should render a link to the NIST website", () => {
        render(<Intro />);
        const nistLink = screen.getByText("NIST Cyber Security Guidance");
        expect(nistLink).toBeInTheDocument();
    });

    it("should render a link to the Cyber Aware Campaign website", () => {
        render(<Intro />);
        const awareLink = screen.getByText("Cyber Aware Campaign");
        expect(awareLink).toBeInTheDocument();
    });

    it("should render a link to the Cyber Essentials Scheme website", () => {
        render(<Intro />);
        const essentialsLink = screen.getByText("Cyber Essentials Scheme");
        expect(essentialsLink).toBeInTheDocument();
    });

    it("should render the legal disclaimer", () => {
        render(<Intro />);
        const disclaimer = screen.getByText("This chatbot should only be used for legitimate, legal purposes.");
        expect(disclaimer).toBeInTheDocument();
    });

    it("should render the external links disclaimer", () => {
        render(<Intro />);
        const externalLinks = screen.getByText("Note: These links will take you to external websites.");
        expect(externalLinks).toBeInTheDocument();
    });

    it("should render the disclaimer for chatbot accuracy", () => {
        render(<Intro />);
        const accuracy = screen.getByText("Note: The information provided by this chatbot is accurate to the best of its knowledge, though it is important to double-check and cross-reference information provided in responses.");
        expect(accuracy).toBeInTheDocument();
    });
});