import styles from "./Intro.module.css";
import { FaCheckCircle } from "react-icons/fa";

export default function Intro() {
    return (
        <div className={styles.introContainer}>
            <div className={styles.introInfo}>
                <h1 className={styles.introHeader}>How It Works</h1>
                <p>The answers generated by this chatbot are supported by a vast and growing knowledgebase of cyber security information.</p>
                <p>Examples of use cases for the chatbot are outlined below:</p>
                <div className={styles.useCases}>
                    <span className={styles.useCase}><FaCheckCircle className={styles.checkIcon} /> Ask questions about cyber security</span>
                    <span className={styles.useCase}><FaCheckCircle className={styles.checkIcon} /> Request information on cyber security topics</span>
                    <span className={styles.useCase}><FaCheckCircle className={styles.checkIcon} /> Learn about newly published vulnerabilities or security alerts</span>
                </div>
            </div>
            <div className={styles.introTryIt}>
                <h1 className={styles.introHeader}>Try It Out</h1>
                <p>Use the conversation window below to interact with the chatbot.</p>
                <p className={styles.disclaimer}>Note: While the aim of this chatbot is to provide correct and up-to-date information, it is important to double-check and cross-reference information provided in responses.</p>
            </div>
        </div>
    );
}